site_name: trackerSpend
repo_url: https://github.com/jdgillespie91/trackerSpend
site_description: Online documentation for trackerSpend.
site_author: Jacob Gillespie
pages:
- ['index.md', 'Welcome!']
- ['what/future.md', 'What am I building?']
- ['what/present.md', 'What am I building?']
- ['what/past.md', 'What am I building?']
- ['notes/deployment.md', 'Deployment notes']
- ['notes/views.md', 'View notes']
theme: readthedocs 
