site_name: trackerSpend
repo_url: https://github.com/jdgillespie91/trackerSpend
site_description: Online documentation for trackerSpend.
site_author: Jacob Gillespie
pages:
- Home: 'index.md'
- What am I building?:
    - 'Future': 'what/future.md'
    - 'Present': 'what/present.md'
    - 'Past': 'what/past.md'
- Best Practice:
    - 'Logging': 'best_practice/logging.md'
    - 'Utils': 'best_practice/utils.md'
- Notes:
    - 'Deployment': 'notes/deployment.md'
    - 'Views': 'notes/views.md'
theme: readthedocs 
